print("Strings are made up of characters grouped together.")
print("This string has 36 characters in it.")
print("String length: ", len("This string has 36 characters in it."))
print("In Python we can append strings together using the '+' operand.")
a = "Hello"
b = " readers!"
print(a + b)

print("Each character within a string belongs to a specific position within that string.")
print("These positions are called indices (singular: index).")
print("Each position, or index, is indicated by a unique number.")
print("The starting position, or index, in any string is 0, then is incremented by 1 for each position after.")
print("For example, string a, 'Hello', has an 'H' at index 0 and an 'o' at position 5.")
print("We can access specific characters within a string if we know their index position!")
print("For example, index 0 in the string Hello is 'H': ", a[0])
print("We can access the 'o' in Hello by calling index 4 of that string: ", a[4])
print("A specific group of characters within a string can also be accessed.")
print("For example, in string 'a' if we call the indices 1 - 4 we can access the character grouping 'read'.")
print(b[1:5])
print("Note that the first index called, 1, is inclusive while the second number called, 5, is not inclusive.")
print("This means that the characters from index 1 up to but not including index 5 will be accessed.")
print("We can even do this from the end of the string, even if we don't know the length of the string.")
print("This is done by using -1 as the index, which can always be used to indicate the last index of a string.")
print("b[-1] will return the character '!': ", b[-1])
print("Using negative indices allows us to access specific characters starting from the end of the string.")
print("In this case each decrement of the index moves us one character closer to the beginning of the string.")
print("For string b: index -1 gives us '!'...index -2 gives us 's'...index -3 gives us 'r': ", b[-1], b[-2], b[-3])
print("We can also access specific character groupings using negative indices.")
print("For string b: b[-5:-1] will return 'ders' while b[-5:] will return 'ders!': ", b[-5:-1], b[-5:])
print("Notice that ommitting the second number is equivalent to saying that 'I want all the characters from the first index until the end of the string'.")
print("Likewise, leaving out the first index number is equivalent to saying 'I want all the characters from the start of the string until but not including the index at the second number given'.")
print("Leaving both the first and second numbers out (including only the ':') just means that we want all characters from beginning to end of the string.")
print("For string a: a[1:] gives us: ", a[1:])
print("For string a: a[:2] gives us: ", a[:2])
print("for string b: b[:] gives us the whole string: ", b[:])